app/base/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String
from sqlalchemy.sql.sqltypes import Boolean

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):
    __table_args__ = {'extend_existing': True}
    __tablename__ = 'User'

    id = Column(Integer, autoincrement=True, primary_key=True)
    username = Column(String(128), unique=True)
    password = Column(Binary)
    isadmin = Column(Boolean, default=False);
    

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

if __name__ == '__main__':
    db.create_all()
    db.session.commit()

app/base/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField,IntegerField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

class ChangePasswordForm(FlaskForm):
    password = PasswordField('Password' , id='pwd_old'      , validators=[DataRequired()])
    newpassword1 = PasswordField('Password' , id='pwd_new1'      , validators=[DataRequired()])
    newpassword2 = PasswordField('Password' , id='pwd_new2'      , validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import ChangePasswordForm, LoginForm, CreateAccountForm
from app.base.models import User
from app.home.utils import *
from app.base.util import *

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):
            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'accounts/login.html', msg='用户名或密码错误', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

# @blueprint.route('/register', methods=['GET', 'POST'])
# def register():
#     login_form = LoginForm(request.form)
#     create_account_form = CreateAccountForm(request.form)
#     if 'register' in request.form:

#         username  = request.form['username']

#         # Check usename exists
#         user = User.query.filter_by(username=username).first()
#         if user:
#             return render_template( 'accounts/register.html', 
#                                     msg='Username already registered',
#                                     success=False,
#                                     form=create_account_form)

#         # else we can create the user
#         user = User(**request.form)
#         db.session.add(user)
#         db.session.commit()

#         return render_template( 'accounts/register.html', 
#                                 msg='User created please <a href="/login">login</a>', 
#                                 success=True,
#                                 form=create_account_form)

#     else:
#         return render_template( 'accounts/register.html', form=create_account_form)

@blueprint.route('/changepassword', methods=['GET', 'POST'])
@login_required
def changepassword():
    change_account_form = ChangePasswordForm(request.form)
    

    if 'changepassword' in request.form:
        password = request.form['password']
        username  = str(current_user)
        
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            if(request.form['newpassword1'] != request.form['newpassword2']):
                return render_template( 'accounts/changepassword.html', msg='新密码两次输入不一样', form=change_account_form)

            user_result = queryToDict(user)
            user_result['password'] = hash_pass(request.form['newpassword1'])
            
            db.session.query(User).filter(User.username == str(current_user)).update(user_result)
            db.session.commit()

            logout_user()
            return redirect(url_for('base_blueprint.login'))

    else:

        return render_template('accounts/changepassword.html', form=change_account_form)




@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('page-403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('page-403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('page-500.html'), 500

app/base/templates/accounts/changepassword.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-4">修改密码</h3>

                    <span class="mb-0 text-muted">
                        {% if msg %}
                            {{ msg | safe }}
                        {% else %}
                            请输入修改后的密码，建议使用强密码
                        {% endif %} 
                    </span>

                    <br />
                    <br />

                    <!-- Hide the form on success -->
                    {% if not success %}
                        <form role="form" method="post" action="">                   

                            <div class="input-group mb-4">
                                {{ form.password(placeholder="旧密码", class="form-control") }}
                            </div>

                            <div class="input-group mb-4">
                                {{ form.newpassword1(placeholder="新密码", class="form-control", type="password") }}
                            </div>

                            <div class="input-group mb-4">
                                {{ form.newpassword2(placeholder="重复新密码", class="form-control", type="password") }}
                            </div>
        
                            <button type="submit" name="changepassword" class="btn btn-primary shadow-2 mb-4">修改密码</button>

                        </form>
                        <p class="mb-2 text-muted">
                            &copy; <a href="/">H资产收集器</a> 
                            - <a href="/">返回首页</a>.
                        </p>
                        <br />
                    {% endif %}

                    
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

app/base/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} 登录 {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-unlock auth-icon"></i>
                    </div>
                    <h3 class="mb-4">登录</h3>

                    <span class="mb-0 text-muted">
                        {% if msg %}
                            {{ msg | safe }}
                        {% else %}
                            请输入账号密码
                        {% endif %} 
                    </span>

                    <br />
                    <br />
                    
                    <form role="form" method="post" action="">

                        {{ form.hidden_tag() }}                    

                        <div class="input-group mb-3">
                            {{ form.username(placeholder="Username", class="form-control") }}
                        </div>
                        
                        <div class="input-group mb-4">
                            {{ form.password(placeholder="Password", class="form-control", type="password") }}
                        </div>
                        
                        <div class="form-group text-left">
                            <div class="checkbox checkbox-fill d-inline">
                                <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
                                <label for="checkbox-fill-a1" class="cr"> 保存凭证</label>
                            </div>
                        </div>
                        <button type="submit" name="login" class="btn btn-primary shadow-2 mb-4">登录</button>

                    </form>

                    
                    <br />
                    <p class="mb-2 text-muted">
                        &copy; 项目地址
                        - <a target="_blank" 
                             href="https://github.com/SiJiDo/H">https://github.com/SiJiDo/H</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

app/base/templates/includes/navigation.html
<!-- NOT IMPLEMENTED -->

app/base/templates/includes/scripts.html
    <!-- Required Js -->
    <script src="/static/assets/plugins/jquery/js/jquery.min.js"></script>
    <script src="/static/assets/js/vendor-all.min.js"></script>
    <script src="/static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/assets/js/pcoded.min.js"></script>
    <link href="/static/bootstrap-fileinput/css/fileinput.min.css" rel="stylesheet" />
    <script src="/static/bootstrap-fileinput/js/fileinput.min.js"></script>

app/base/templates/includes/sidebar.html
    <nav class="pcoded-navbar navbar-collapsed">
        <div class="navbar-wrapper">
            <div class="navbar-brand header-logo">
                <a target="_blank" 
                   href="" class="b-brand">
                    <div class="b-bg">
                        <div style="color: white;">H</div>
                    </div>
                    <span class="b-title align-items-center">资产管理器</span>
                </a>
                <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
            </div>
            <div class="navbar-content scroll-div">
                <ul class="nav pcoded-inner-navbar">
                    <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                        class="nav-item {% if 'index' in segment %} active {% endif %}">
                        <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">首页</span></a>
                    </li>
                    
                    <li class="nav-item pcoded-menu-caption">
                        <label>资产管理</label>
                    </li>

                    <li data-username="target" 
                     class="nav-item {% if 'target' == segment %} active {% endif %}">
                    <a href="/target" class="nav-link "><span class="pcoded-micon"><i class="feather icon-crosshair"></i></span><span class="pcoded-mtext">资产列表</span></a></li>

                    <li data-username="targetadd" 
                     class="nav-item {% if 'targetadd' == segment %} active {% endif %}">
                    <a href="/targetadd" class="nav-link "><span class="pcoded-micon"><i class="feather icon-edit"></i></span><span class="pcoded-mtext">添加资产</span></a></li>


                    <li class="nav-item pcoded-menu-caption">
                        <label>扫描结果</label>
                    </li>
                    <li data-username="subdomain" 
                    class="nav-item {% if 'subdomain' in segment %} active {% endif %}">
                    <a href="/subdomain" class="nav-link "><span class="pcoded-micon"><i class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">子域名信息</span></a></li>
                
                
                    <li data-username="port" 
                     class="nav-item {% if 'port' in segment %} active {% endif %}">
                    <a href="/port" class="nav-link "><span class="pcoded-micon"><i class="feather icon-radio"></i></span><span class="pcoded-mtext">端口信息</span></a></li>

                    <li data-username="url" 
                    class="nav-item {% if 'http' in segment %} active {% endif %}">
                    <a href="/http" class="nav-link "><span class="pcoded-micon"><i class="feather icon-airplay"></i></span><span class="pcoded-mtext">站点信息</span></a></li>
                
                
                    <li data-username="dirb" 
                     class="nav-item {% if 'dirb' in segment %} active {% endif %}">
                    <a href="/dirb" class="nav-link "><span class="pcoded-micon"><i class="feather icon-map"></i></span><span class="pcoded-mtext">路径信息</span></a></li>

                    <li data-username="vuln" 
                    class="nav-item {% if 'vuln' in segment %} active {% endif %}">
                    <a href="/vuln" class="nav-link "><span class="pcoded-micon"><i class="feather icon-bell"></i></span><span class="pcoded-mtext">漏洞信息</span></a></li>
                    <li class="nav-item pcoded-menu-caption">
                        <label>扫描设置</label>
                    </li>
                    <li data-username="scanmethod" 
                        class="nav-item {% if 'scanmethod' in segment %} active {% endif %}">
                        <a href="/scanmethod" class="nav-link "><span class="pcoded-micon"><i class="feather icon-layers"></i></span><span class="pcoded-mtext">扫描模式配置</span></a></li>
                    
                    
                        <li data-username="scancron" 
                         class="nav-item {% if 'scancron' in segment %} active {% endif %}">
                        <a href="/scancron" class="nav-link "><span class="pcoded-micon"><i class="feather icon-watch"></i></span><span class="pcoded-mtext">扫描周期配置</span></a></li>
                    
                        <li class="nav-item pcoded-menu-caption">
                            <label>快捷插件</label>
                        </li>
                            <li data-username="beian" 
                             class="nav-item {% if 'icp' in segment %} active {% endif %}">
                            <a href="/icp" class="nav-link "><span class="pcoded-micon"><i class="feather icon-search"></i></span><span class="pcoded-mtext">备案信息查询</span></a></li>

                            <li data-username="hostcrack" 
                             class="nav-item {% if 'hostcrack' in segment %} active {% endif %}">
                            <a href="/hostcrack" class="nav-link "><span class="pcoded-micon"><i class="feather icon-minimize-2"></i></span><span class="pcoded-mtext">host碰撞</span></a></li>

                            <li data-username="apkinfo" 
                            class="nav-item {% if 'apkget' in segment %} active {% endif %}">
                            <a href="/apkget" class="nav-link "><span class="pcoded-micon"><i class="feather icon-tablet"></i></span><span class="pcoded-mtext">apk域名提取</span></a></li>
    
                            <!-- <li data-username="fofa" 
                            class="nav-item {% if 'fofaget' in segment %} active {% endif %}">
                            <a href="/fofaget" class="nav-link "><span class="pcoded-micon"><i class="feather icon-facebook"></i></span><span class="pcoded-mtext">fofa查询</span></a></li> -->
                    <li class="nav-item pcoded-menu-caption">
                        <label>系统设置</label>
                    </li>
                    
                    <!-- <li data-username="userlist" 
                     class="nav-item {% if 'userlist' in segment %} active {% endif %}">
                    <a href="/page-blank" class="nav-link"><span class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">用户列表</span></a></li> -->

                    <li data-username="changepassword" 
                     class="nav-item {% if 'changepassword' in segment %} active {% endif %}">
                    <a href="/changepassword" class="nav-link"><span class="pcoded-micon"><i class="feather icon-refresh-cw"></i></span><span class="pcoded-mtext">修改密码</span></a></li>
                    
                    <li data-username="config" 
                     class="nav-item {% if 'sysconfig' in segment %} active {% endif %}">
                    <a href="/sysconfig" class="nav-link"><span class="pcoded-micon"><i class="feather icon-settings"></i></span><span class="pcoded-mtext">系统设置</span></a></li>

                    <li data-username="退出登陆" class="nav-item">
                    <a href="{{ url_for('base_blueprint.logout') }}" class="nav-link"><span class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">登出</span></a></li>
                </ul>
            </div>
        </div>
    </nav>

app/base/templates/layouts/base-fullscreen.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>
        Flask Datta Able - {% block title %}{% endblock %} | AppSeed
    </title>
    <!-- HTML5 Shim and Respond.js IE10 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 10]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="canonical" href="https://appseed.us/admin-dashboards/flask-dashboard-dattaable">
    
    <meta name="description" content="Datta Able Bootstrap admin template made using Bootstrap 4 and it has huge amount of ready made feature, UI components, pages which completely fulfills any dashboard needs." />
    <meta name="keywords" content="admin templates, bootstrap admin templates, bootstrap 4, dashboard, dashboard templets, sass admin templets, html admin templates, responsive, bootstrap admin templates free download,premium bootstrap admin templates, datta able, datta able bootstrap admin template, free admin theme, free dashboard template"/>
    <meta name="author" content="CodedThemes"/>

    <!-- Favicon icon -->
    <link rel="icon" href="/static/assets/images/favicon.ico" type="image/x-icon">
    <!-- fontawesome icon -->
    <link rel="stylesheet" href="/static/assets/fonts/fontawesome/css/fontawesome-all.min.css">
    <!-- animation css -->
    <link rel="stylesheet" href="/static/assets/plugins/animation/css/animate.min.css">
    <!-- vendor css -->
    <link rel="stylesheet" href="/static/assets/css/style.css">

    <!-- Specific CSS goes HERE -->
    {% block stylesheets %}{% endblock stylesheets %}

</head>

<body>
    
    {% block content %}{% endblock content %}

    {% include 'includes/scripts.html' %}

    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}    

</body>
</html>

app/base/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>
        H - {% block title %}{% endblock %}
    </title>
    <!-- HTML5 Shim and Respond.js IE10 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 10]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="canonical" href="https://appseed.us/admin-dashboards/flask-dashboard-dattaable">
    
    <meta name="description" content="Datta Able Bootstrap admin template made using Bootstrap 4 and it has huge amount of ready made feature, UI components, pages which completely fulfills any dashboard needs." />
    <meta name="keywords" content="admin templates, bootstrap admin templates, bootstrap 4, dashboard, dashboard templets, sass admin templets, html admin templates, responsive, bootstrap admin templates free download,premium bootstrap admin templates, datta able, datta able bootstrap admin template, free admin theme, free dashboard template"/>
    <meta name="author" content="CodedThemes"/>

    <!-- Favicon icon -->
    <link rel="icon" href="/static/assets/images/favicon.ico" type="image/x-icon">
    <!-- fontawesome icon -->
    <link rel="stylesheet" href="/static/assets/fonts/fontawesome/css/fontawesome-all.min.css">
    <!-- animation css -->
    <link rel="stylesheet" href="/static/assets/plugins/animation/css/animate.min.css">
    <!-- vendor css -->
    <link rel="stylesheet" href="/static/assets/css/style.css">

    <!-- Specific CSS goes HERE -->
    {% block stylesheets %}{% endblock stylesheets %}

</head>

<body>

    <!-- [ Pre-loader ] start -->
    <div class="loader-bg">
        <div class="loader-track">
            <div class="loader-fill"></div>
        </div>
    </div>    
    
    <!-- Top Bar -->
    {% include 'includes/navigation.html' %}

    <!-- SideBar -->
    {% include 'includes/sidebar.html' %}

    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            {% block content %}{% endblock content %}

        </div>
    </div>

    {% include 'includes/scripts.html' %}

    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}

</body>
</html>